language: node_js
node_js:
  - "4.4"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install karma --save-dev
  - npm install karma-jasmine karma-chrome-launcher --save-dev
  - npm install jasmine-node --save-dev